---
- name: Install standard packages
  package:
    name: "{{ item }}"
    state: present
  become: "{{ 'no' if ansible_distribution == 'MacOSX' else 'yes' }}"
  with_items:
    - git
    - zsh
    - docker
    - tmux
    - curl

- name: Install Oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Install Oh-my-zsh theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1

- name: Install Oh-my-zsh plugins
  git:
    repo: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ (item|basename()|splitext)[0] }}"
    depth: 1
  with_items:
    - "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    - "https://github.com/zsh-users/zsh-autosuggestions.git"
    - "https://github.com/zsh-users/zsh-completions.git"

# - name: Install Chezmoi
#   shell: curl -sfL https://git.io/chezmoi | sh
#   args:
#     chdir: "{{ ansible_env.HOME }}"
#     creates: "{{ ansible_env.HOME }}/bin/chezmoi"

# - name: Initialize Chezmoi
#   git:
#     repo: https://github.com/AaronNBrock/dotfiles.git
#     dest: "{{ ansible_env.HOME }}/.local/share/chezmoi"

# - name: Apply Chezmoi
#   shell: "{{ ansible_env.HOME }}/bin/chezmoi update"

# - name: Set remote to ssh
#   git_config:
#     name: remote.origin.url
#     repo: "{{ ansible_env.HOME }}/.local/share/chezmoi"
#     scope: local
#     value: git@github.com:AaronNBrock/dotfiles.git

- name: Create .ssh directory
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: 0700

- name: Generate ssh key
  openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/id_rsa"
    comment: "{{ ansible_user_id }}@{{ ansible_hostname }}"

- name: Set id_rsa permissions
  file:
    path: "{{ ansible_env.HOME }}/.ssh/id_rsa"
    mode: "1600"

- name: Set id_rsa.pub permissions
  file:
    path: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
    mode: "1644"
